# /etc/nginx/sites-available/default

server {
    listen 80;
    server_name n8n.dashboard.com;
    
    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
    
}